WebAPI/MVC/Controllers/FeedbacksController.cs
using BusinessLayer;
using DataLayer;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers;

public class FeedbacksController : Controller
{
    private readonly IDb<Feedback, int> _context;
    private readonly UserManager<User> _userManager;

    public FeedbacksController(FeedbackContext context, UserManager<User> userManager)
    {
        _context = context;
        _userManager = userManager;
    }

    // GET: Feedbacks
    public async Task<IActionResult> Index()
    {
        return View(await _context.ReadAll(true, true));
    }


    // GET: Feedbacks/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Feedbacks/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Rating,Review")] Feedback feedback)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user != null) feedback.User = user;
            feedback.Created = DateTime.Now;
            await _context.Create(feedback);
            return RedirectToAction(nameof(Index));
        }

        return View(feedback);
    }
}

WebAPI/MVC/Views/Feedbacks/Create.cshtml
@model BusinessLayer.Feedback

@{
    ViewData["Title"] = "Create";
}

<div class="flex-row text-center mt-4">
    <h3>Leave a Review</h3>

</div>
<div class="row justify-content-center align-items-center mb-5">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input type="number" asp-for="Rating" min="1" max="5" class="form-control"/>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Review" class="control-label"></label>
                <input type="text" asp-for="Review" class="form-control"/>
                <span asp-validation-for="Review" class="text-danger"></span>
            </div>
            <div class="form-group align-items-center text-center justify-content-between flex-row mt-3">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

WebAPI/MVC/Views/Feedbacks/Index.cshtml
@model IEnumerable<BusinessLayer.Feedback>

@{
    ViewData["Title"] = "Testimonial";
}
<section class="client_section layout_padding">
    <div class="container">
        <div class="heading_container heading_center" style="flex-direction:row;justify-content:space-between">
            <a asp-action="Create" asp-controller="Feedbacks" class="btn btn-primary">Add Review</a>
            <h2 style="justify-self:center;margin: 0 auto;text-align:center">
                Reviews
            </h2>
        </div>
    </div>
    <div class="container px-0">
        <div id="customCarousel2" class="carousel  carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                @{
                    var isFirst = true;
                }
                @foreach (var item in Model)
                {
                    <div class="carousel-item @(isFirst ? "active" : "")">
                        <div class="box">
                            <div class="client_info">
                                <div class="client_name">
                                    <h5>
                                        @(item.User != null ? item.User.Name : "Anonymous")
                                    </h5>
                                    <h6>
                                        @for (var i = 1; i <= 5; i++)
                                        {
                                            if (i <= item.Rating)
                                            {
                                                <i class="fa fa-star text-warning"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-star text-muted"></i>
                                            }
                                        }
                                    </h6>
                                </div>
                                <i class="fa fa-quote-left" aria-hidden="true"></i>
                            </div>
                            <p>
                                @Html.DisplayFor(itemReview => item.Review)
                            </p>
                        </div>
                    </div>
                    isFirst = false;
                }


            </div>
            <div class="carousel_btn-box">
                <a class="carousel-control-prev" href="#customCarousel2" role="button" data-slide="prev">
                    <i class="fa fa-angle-left" aria-hidden="true"></i>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#customCarousel2" role="button" data-slide="next">
                    <i class="fa fa-angle-right" aria-hidden="true"></i>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</section>
<!-- end client section -->
<script src="~/js/jquery-3.4.1.min.js"></script>
<script src="~/js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<script src="~/js/custom.js"></script>